# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
        types: [file]
        files: \.(json|user.*|group.*)$
    -   id: pretty-format-json
        args: ['--autofix', '--indent=2']
        types: [file]
        files: \.(json|user.*|group.*)$
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-case-conflict
    -   id: detect-aws-credentials
        args: ['--allow-missing-credentials']
    -   id: detect-private-key
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
-   repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.2.16
    hooks:
    -   id: rumdl-fmt
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    -   id: shellcheck
