# Name Service Switch configuration
# See nsswitch.conf(5) for details

passwd:     files systemd sss
shadow:     files systemd sss
group:      files systemd sss
gshadow:    files systemd sss

hosts:      files myhostname resolve [!UNAVAIL=return] dns
networks:   files

protocols:  files
services:   files sss
ethers:     files
rpc:        files

netgroup:   sss
automount:  sss
