# Core user home directory and SSH key
d /var/home/core 0750 core core - -
d /var/home/core/.ssh 0700 core core - -
f~ /var/home/core/.ssh/authorized_keys 0600 core core - c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUhvQVNNWHphNHJJdTNPRmFWeE9PR3pQWmVLaERDZ09XaWE4QTY2TGFFUVAgYWJ5cm5lNTUvaG9tZWxhYgo=
