version: 1
base_url: "http://systemd-jellyfin:8096"
system: {}
startup:
  completeStartupWizard: true
library:
  virtualFolders:
    - name: "Movies"
      collectionType: "movies"
      libraryOptions:
        pathInfos:
          - path: "/media/Movies"
users:
  - name: "abyrne55"
    passwordFile: /run/credentials/abyrne55-jellyfin-password
    policy:
      isAdministrator: true
# encoding, plugins, branding — add as needed
