name: reviewdog
on: [pull_request]
jobs:
  misspell:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: reviewdog/action-misspell@ba7ac4030fa6812f8c8b2d4e516af8bc99553c32 # v1.28.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          locale: "US"
          fail_level: warning
  actionlint:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: reviewdog/action-actionlint@320fcdd9c860767cf17fab3b20e22e739d5d02b8 # v1.76.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_level: warning
