name: validate-systemd

on:
  workflow_run:
    workflows: [container]
    types: [completed]

jobs:
  verify-systemd:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install podman
        run: sudo apt-get install -y podman

      - name: Verify systemd units
        run: make verify-systemd-from-ghcr
        env:
          REMOTE_IMAGE: ghcr.io/abyrne55/homelab:${{ github.event.workflow_run.head_branch }}
