name: validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quadlets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install podman
        run: sudo apt-get install -y podman

      - name: Validate quadlet files
        run: make verify-quadlets
